#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.4.33f1_c9b2b02eeeef"
#define UNITY_VERSION_FULL_NICE "2019.4.33f1 (c9b2b02eeeef)"
#define UNITY_VERSION_BLD 13218480
#define UNITY_VERSION_DATE 1637349095
#define UNITY_VERSION_WIN "2019.4.33.13218480"
#define UNITY_VERSION_BRANCH "2019.4/staging"
